import { MockBooking } from "../types/mock-bookings";

export const mockBookings: MockBooking[] = [
  {
    id: "1",
    clientName: "John Smith",
    company: "Acme Corp",
    serviceType: "airport",
    pickup: "10 Downing Street, Westminster, London SW1A 2AA",
    destination: "Heathrow Terminal 5",
    date: "2025-01-15",
    time: "06:30",
    passengers: 2,
    status: "confirmed",
    notes: "Flight BA117, terminal 5",
  },
  {
    id: "2",
    clientName: "Emma Williams",
    serviceType: "private",
    pickup: "221B Baker Street, Marylebone, London NW1 6XE",
    destination: "Gatwick Airport North Terminal",
    date: "2025-01-16",
    time: "14:00",
    passengers: 4,
    status: "pending",
  },
  {
    id: "3",
    clientName: "Yuki Tanaka",
    company: "TechVision Ltd",
    serviceType: "corporate",
    pickup: "Canary Wharf, London E14",
    destination: "The Shard, 32 London Bridge Street, London SE1 9SG",
    date: "2025-01-17",
    time: "09:00",
    passengers: 3,
    status: "completed",
    notes: "Board meeting, 3 executives",
  },
  {
    id: "4",
    clientName: "Sarah Johnson",
    company: "Brighton Academy",
    serviceType: "group",
    pickup: "Brighton Railway Station, Queens Road, Brighton BN1 1NP",
    destination: "Stansted Airport",
    date: "2025-01-18",
    time: "05:45",
    passengers: 24,
    status: "confirmed",
    notes: "School trip to Paris, 2 minibuses needed",
  },
  {
    id: "5",
    clientName: "Michael Brown",
    serviceType: "airport",
    pickup: "15 Kensington High Street, Kensington, London W8 4PT",
    destination: "Luton Airport",
    date: "2025-01-19",
    time: "11:30",
    passengers: 1,
    status: "cancelled",
    notes: "Client cancelled due to flight change",
  },
  {
    id: "6",
    clientName: "Olivia Taylor",
    company: "Greenfield Events",
    serviceType: "private",
    pickup: "The Ritz London, 150 Piccadilly, London W1J 9BR",
    destination: "Windsor Castle, Windsor SL4 1NJ",
    date: "2025-01-20",
    time: "16:00",
    passengers: 6,
    status: "pending",
    notes: "Wedding party, flower arrangements in vehicle",
  },
  {
    id: "7",
    clientName: "James Wilson",
    company: "London Finance Group",
    serviceType: "corporate",
    pickup: "Bank of England, Threadneedle Street, London EC2R 8AH",
    destination: "London City Airport",
    date: "2025-01-21",
    time: "07:15",
    passengers: 2,
    status: "confirmed",
  },
  {
    id: "8",
    clientName: "Raj Patel",
    serviceType: "group",
    pickup: "Wembley Stadium, Olympic Way, Wembley HA9 0WS",
    destination: "221B Baker Street, Marylebone, London NW1 6XE",
    date: "2025-01-22",
    time: "21:00",
    passengers: 12,
    status: "completed",
    notes: "Post-event transport, 1 minibus",
  },
  {
    id: "9",
    clientName: "Robert Davis",
    company: "Global Education Partners",
    serviceType: "airport",
    pickup: "University College London, Gower Street, London WC1E 6BT",
    destination: "Gatwick Airport South Terminal",
    date: "2025-01-23",
    time: "13:45",
    passengers: 3,
    status: "pending",
    notes: "Academic conference, 3 professors",
  },
  {
    id: "10",
    clientName: "Leila Mansour",
    serviceType: "private",
    pickup: "Harrods, 87-135 Brompton Road, Knightsbridge, London SW1X 7XL",
    destination: "Heathrow Terminal 3",
    date: "2025-01-24",
    time: "18:30",
    passengers: 2,
    status: "confirmed",
    notes: "VIP client, luxury vehicle requested",
  },
];
